### 根据id获取员工
GET http://localhost:8080/api/v1/employee/1
Accept: application/json

### 根据id删除员工
DELETE http://localhost:8080/api/v1/employee/8
Accept: application/json

### 新增员工
POST http://localhost:8080/api/v1/employee
Content-Type: application/json
Accept: application/json

{
  "name": "to2bage",
  "age": 50,
  "address": "庐阳区",
  "email": "to2bage@qq.com",
  "gender": "男",
  "salary": "7032.12",
  "birth": "1975/12/30 13:30:00"
}

### 修改员工
PUT http://localhost:8080/api/v1/employee
Content-Type: application/json
Accept: application/json

{
  "id": 8,
  "name": "呵呵",
  "age": 58,
  "address": "中元区"
}

### 查询所有的员工
GET http://localhost:8080/api/v1/employees
Accept: application/json