### 根据id获取员工
GET http://localhost:8080/api/v1/employee/1
Accept: application/json

### 根据id删除员工
DELETE http://localhost:8080/api/v1/employee/8
Accept: application/json

### 新增员工
POST http://localhost:8080/api/v1/employee
Content-Type: application/json
Accept: application/json

{
  "name": "哈哈",
  "age": 28,
  "address": "上元区",
  "email": "hah@qq.com",
  "gender": "女",
  "salary": "4949.49"
}

### 修改员工
PUT http://localhost:8080/api/v1/employee
Content-Type: application/json
Accept: application/json

{
  "id": 8,
  "name": "呵呵",
  "age": 58,
  "address": "中元区"
}

### 查询所有的员工
GET http://localhost:8080/api/v1/employees
Accept: application/json